CFLAGS=-O -Wuninitialized -Werror

all: example-codelock example-buffer example-small

example-codelock: example-codelock.c ../include/pt.h ../include/lc.h

example-buffer: example-buffer.c ../include/pt.h ../include/lc.h

example-small: example-small.c ../include/pt.h ../include/lc.h
